### ISSUE TITLE
add a function to push SFW setu plz

### ISSUE THREAD

**Issue by Saika1997** [Ivanlon30000/sesebot#1]
add a function to push SFW setu plz

**Comment by Ivanlon30000** [comment]
in progress

**Comment by Saika1997** [comment]
My colleagues saw the setu in my computer and asked me for setu
So awkward

**Comment by Ivanlon30000** [comment]
A "sanity level" filter has been added.

**Comment by Saika1997** [comment]
Thank you。 Now，I can sese everyday
